/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-05-25 08:59:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pagina_005fcaballos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"pagina_caballos.css\">\r\n");
      out.write("    <title>centro hipico medina del campo</title>\r\n");
      out.write("    <script  type=\"text/javascript\"  src=\"1.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("      <!--  barra de navegación-->\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"pagina_principal.jsp\">Centro hipico medina del campo</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"pagina_caballos.jsp\">caballos</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"pagina_herramientas.jsp\">herramientas</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"pagina_compra.jsp\">compra de articulos (provisional)</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"pagina_peluqueria.jsp\">peluqueria equina</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("          <h1 id=\"titulo\">\r\n");
      out.write("        <strong>CENTRO HIPICO MEDINA DEL CAMPO</strong>\r\n");
      out.write("      </h1>\r\n");
      out.write("   <!--  foto del login para pupilaje-->   \r\n");
      out.write("        <a href=\"pagina_inicio_formulario.jsp\">\r\n");
      out.write("        <img id=log src=\"img/caballo.jpg\"/>\r\n");
      out.write("      </a>\r\n");
      out.write("      <div id=\"photos\">\r\n");
      out.write("      <!-- fotos de todos los caballos-->\r\n");
      out.write("      <div id=\"photo_marijuli\">\r\n");
      out.write("      <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Marijuli\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"marijuli\" >MARRIJULI </h2>\r\n");
      out.write("      <button type=\"submit\">\r\n");
      out.write("      <img id=\"photo1\" src=\"img/IMG-20210726-WA0004.jpg\"/>\r\n");
      out.write("      </button>\r\n");
      out.write("	 <!--  <input name=\"enviar\" type=\"submit\"/>-->\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>      \r\n");
      out.write("      <div id=\"photo_chicuelo\">\r\n");
      out.write("       <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Chiquelo\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2  id=\"chicuelo\" >CHICUELO</h2>\r\n");
      out.write("      <img id=\"photo2\" src=\"img/IMG-20210726-WA0005.jpg\"/>\r\n");
      out.write("       <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>  \r\n");
      out.write("      <div id=\"photo_leticia\">\r\n");
      out.write("       <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Leticia\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"leticia\">LETICIA</h2>\r\n");
      out.write("      <img id=\"photo3\" src=\"img/IMG-20210821-WA0038.jpg\"/>\r\n");
      out.write("	  <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("	  </form> 	\r\n");
      out.write("      </div>  \r\n");
      out.write("      <div id=\"photo_pia\">\r\n");
      out.write("       <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Pia\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"pia\">PIA</h2>\r\n");
      out.write("      <img id=\"photo4\" src=\"img/IMG-20210726-WA0004.jpg\"/>\r\n");
      out.write("	  <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div> \r\n");
      out.write("       <div id=\"photo_valentina\">\r\n");
      out.write("        <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Valentina\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"valentina\">VALENTINA</h2>\r\n");
      out.write("      <img id=\"photo5\" src=\"img/IMG-20210901-WA0008.jpg\"/>\r\n");
      out.write("      <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("	  </form> \r\n");
      out.write("      </div> \r\n");
      out.write("      <div id=\"photo_fermin\">\r\n");
      out.write("       <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Fermin\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"fermin\">FERMIN</h2>\r\n");
      out.write("      <img id=\"photo6\" src=\"img/IMG-20210726-WA0004.jpg\"/>\r\n");
      out.write("	  <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("	  </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"photo_tierra\">\r\n");
      out.write("       <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Tierra\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"tierra\">TIERRA</h2>\r\n");
      out.write("      <img id=\"photo7\" src=\"img/IMG-20210726-WA0005.jpg\"/>\r\n");
      out.write("	  <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("	  </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"photo_africa\">\r\n");
      out.write("       <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Africa\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"africa\">AFRICA</h2>\r\n");
      out.write("      <img id=\"photo8\" src=\"img/IMG-20210821-WA0038.jpg\"/>\r\n");
      out.write("      <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("	  </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"photo_bombon\">\r\n");
      out.write("      <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Bombon\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"bombon\">BOMBON</h2>\r\n");
      out.write("      <img id=\"photo9\" src=\"img/IMG-20210726-WA0004.jpg\"/>\r\n");
      out.write("      <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>\r\n");
      out.write("       <div id=\"photo_armonia\">\r\n");
      out.write("        <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Armonia\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"armonia\">ARMONIA</h2>\r\n");
      out.write("      <img id=\"photo10\" src=\"img/IMG-20210726-WA0004.jpg\"/>\r\n");
      out.write("      <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>\r\n");
      out.write("       <div id=\"photo_gucci\">\r\n");
      out.write("        <form action=\"caballos_clase\" method=\"get\">\r\n");
      out.write("      <input value=\"Gucci\"name=\"1\" type=\"hidden\"/>\r\n");
      out.write("      <h2 id=\"gucci\">GUCCI</h2>\r\n");
      out.write("      <img id=\"photo11\" src=\"img/IMG-20210821-WA0038.jpg\"/>\r\n");
      out.write("      <input name=\"enviar\" type=\"submit\"/>\r\n");
      out.write("      </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
